version: '3.8'
services:
  server:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html

  node:
    image: node:20-alpine
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
